Songs = [
    {
        id: 0,
        urlSong: "./music/mapmo.mp3",
        urlPoster: "./img/mapmo.jpg",
        nameSinger: "Phí Phương Anh",
        nameSong: "Mập Mờ",
        timeSong: "5:00",
    },
    {
        id: 1,
        urlSong: "./music/buocquamuacodon.mp3",
        urlPoster: "./img/buocquamuacodon.jpg",
        nameSinger: "Vũ",
        nameSong: "Bước Qua Mùa Cô Đơn",
        timeSong: "5:42",
    },
    {
        id: 2,
        urlSong: "./music/daunhatlalangim.mp3",
        urlPoster: "./img/daunhatlalangim.jpg",
        nameSinger: "Erik",
        nameSong: "Đau Nhất Là Lặng Im",
        timeSong: "5:05",
    },
    {
        id: 3,
        urlSong: "./music/dungquentenanh.mp3",
        urlPoster: "./img/dungquentenanh.jpg",
        nameSinger: "Hoa Vinh",
        nameSong: "Đừng Quên Tên Anh",
        timeSong: "6:33",
    },
    {
        id: 4,
        urlSong: "./music/ngaydautien.mp3",
        urlPoster: "./img/ngaydautien.jpg",
        nameSinger: "Đức Phúc",
        nameSong: "Ngày Đầu Tiên",
        timeSong: "5:39",
    },
    {
        id: 5,
        urlSong: "./music/saulunganhcoaikia.mp3",
        urlPoster: "./img/saulunganhcoaikia.jpg",
        nameSinger: "Thiều Bảo Trâm",
        nameSong: "Sau Lưng Anh Có Ai Kìa",
        timeSong: "5:13",
    },
    {
        id: 6,
        urlSong: "./music/chayvekhocvoianh.mp3",
        urlPoster: "./img/yeuduongkhoquathichayvekhocvoianh.jpg",
        nameSinger: "Erik",
        nameSong: "Yêu Đương Khó Quá Thì Chạy Về Khóc Với Anh",
        timeSong: "6:10",
    },
]